# Generated by Django 3.2 on 2021-06-22 13:45

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('code', models.CharField(default=registration.models.code_generator, max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registration', serialize=False, to='user.user')),
            ],
        ),
    ]
