# Generated by Django 3.2 on 2021-06-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='subject',
            field=models.CharField(choices=[('R', 'registration'), ('P', 'password_reset')], default='R', max_length=1),
        ),
    ]
