# Generated by Django 3.2 on 2021-06-14 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True,
                                         related_name='liked_Posts',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
