# Generated by Django 3.2 on 2021-06-11 13:47

import django.core.validators
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True,
                                    upload_to=user.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, null=True,
                                    upload_to=user.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[
                django.core.validators.RegexValidator(
                    message="Phone number must be entered in the format: "
                            "'+999999999'. Up to 15 digits allowed.",
                    regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='things_user_likes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
