# Generated by Django 3.2 on 2021-06-22 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rejected',
            field=models.ManyToManyField(blank=True, related_name='_user_user_rejected_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
